<a href="https://colab.research.google.com/github/Abdullah-NI/NoteBooks/blob/main/03Numphy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numphy=> Numerical python

In [ ]:
import numpy as np

**List vs Numpy -time taken**

In [ ]:
from time import process_time

Time taken by list

In [ ]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0012688259999995566


Time taken by numpy array

In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5 # adding 5 in evey value of aray
end_time=process_time()
print(end_time-start_time)


0.0012005909999999176


Numpy array

In [ ]:
#list
list1=[1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating 1 dim array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)  #data type
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholer in numpy array=>  means arry ko kis value se initialize karna hi

In [ ]:
#creating a numpy array of zeros
x=np.zeros((4,5))   #no of rows 4, no of column 5
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#creating num array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of paricular value
z=np.full((4,5),500)
print(z)

[[500 500 500 500 500]
 [500 500 500 500 500]
 [500 500 500 500 500]
 [500 500 500 500 500]]


In [ ]:
# create an identitiy matrix
a=np.eye(7)  # yah only oder of matrix diya bcz identy marix is square matrix
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#creating a numpy array with random value
b=np.random.random((3,4))       #random value comes between 0 to 1
print(b)

[[0.06837714 0.6125912  0.98799873 0.09732081]
 [0.36172944 0.4498573  0.61352424 0.54202676]
 [0.0363646  0.2541477  0.10539604 0.37145486]]


In [ ]:
#random integer values array with in a specific range
c=np.random.randint(10,100,(3,4))   #integer range between 10 to 100 ,,,, no of rows=3 and col=4
print(c)

[[84 90 28 19]
 [83 80 97 26]
 [93 83 84 63]]


In [ ]:
#array of evenly space value--> specifiyn no of value required
d=np.linspace(10,30,5)   #here 5 is no of value required
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spacd vaulue---. specifying the step
e=np.arange(10,30,2)   # here 2 is step
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [ ]:
#converting a list to numpy array
list2=[10,20,30,40,50]
print("it is list: ",list2)
np_array=np.asarray(list2)
print("it is array: ",np_array)
type(np_array)

it is list:  [10, 20, 30, 40, 50]
it is array:  [10 20 30 40 50]


numpy.ndarray

In [ ]:
tup2=(10,20,30,40,50)
print("it is tuple: ",tup2)
np_array=np.asarray(tup2)
print("it is array: ",np_array)
type(np_array)

it is tuple:  (10, 20, 30, 40, 50)
it is array:  [10 20 30 40 50]


numpy.ndarray

**Analysing a numpy array**




In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[26 13 48 29 50]
 [49 49 41 33 29]
 [56 71 73 19 65]
 [17 49 40 54 23]
 [84 58 88 79 89]]


In [ ]:
#array dimension
print(c.shape)

(5, 5)


In [ ]:
#number of dimention
print(c.ndim)

2


In [ ]:
#number of element in aarry
print(c.size)

25


In [ ]:
#checking data type of values in array
print(c.dtype)

int64


**Mathmatical opration on numpy array**

In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2) #concatinating list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 3 7]
 [0 7 7]
 [4 8 1]]
[[14 18 16]
 [17 12 13]
 [12 18 13]]


In [ ]:
print(a+b) # addition by element wise
print(a-b)
print(a*b)
print(a/b)

[[16 21 23]
 [17 19 20]
 [16 26 14]]
[[-12 -15  -9]
 [-17  -5  -6]
 [ -8 -10 -12]]
[[ 28  54 112]
 [  0  84  91]
 [ 48 144  13]]
[[0.14285714 0.16666667 0.4375    ]
 [0.         0.58333333 0.53846154]
 [0.33333333 0.44444444 0.07692308]]


In [ ]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 7 2]
 [2 9 4]
 [7 7 0]]
[[15 17 18]
 [17 14 18]
 [11 16 14]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[18 24 20]
 [19 23 22]
 [18 23 14]]
[[-12 -10 -16]
 [-15  -5 -14]
 [ -4  -9 -14]]
[[ 45 119  36]
 [ 34 126  72]
 [ 77 112   0]]
[[0.2        0.41176471 0.11111111]
 [0.11764706 0.64285714 0.22222222]
 [0.63636364 0.4375     0.        ]]


**Array Manipulation**

In [ ]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 6 2]
 [2 7 0]]
(2, 3)


In [ ]:
#transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[1 2]
 [6 7]
 [2 0]]
(3, 2)


In [ ]:
#another way to find transpose
trans2=array.T
print(trans2)
print(trans2.shape)

[[1 2]
 [6 7]
 [2 0]]
(3, 2)


In [ ]:
#reshape the array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 1 6]
 [5 4 9]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[2 1]
 [6 5]
 [4 9]]
(3, 2)


This is the and