<a href="https://colab.research.google.com/github/Abdullah-NI/NoteBooks/blob/main/03Numphy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numphy=> Numerical python

In [2]:
import numpy as np

**List vs Numpy -time taken**

In [3]:
from time import process_time

This line of code imports the process_time function from the time module in Python.

**Purpose of process_time:**

The process_time function is used to measure the CPU time used by the current process. This is the time the actual CPU spends executing your code (including the time used by any child processes).

**How it's used:**


start_time = process_time()  # Capture start time

... (Your code) ...

end_time =process_time()    # Capture end time

elapsed_time = end_time - start_time  #Calculate the CPU time

print("Elapsed CPU time:", elapsed_time)


Time taken by list

In [4]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0020036089999999618


Time taken by numpy array

In [5]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5 # adding 5 in evey value of aray
end_time=process_time()
print(end_time-start_time)


0.0030793099999999463


Numpy array

In [6]:
#list
list1=[1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [7]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating 1 dim array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
a.shape

(5,)

In [10]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)  #data type
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholer in numpy array=>  means arry ko kis value se initialize karna hi

In [13]:
#creating a numpy array of zeros
x=np.zeros((4,5))   #no of rows 4, no of column 5
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#creating num array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of paricular value
z=np.full((4,5),500)
print(z)

[[500 500 500 500 500]
 [500 500 500 500 500]
 [500 500 500 500 500]
 [500 500 500 500 500]]


In [16]:
# create an identitiy matrix
a=np.eye(7)  # yah only oder of matrix diya bcz identy marix is square matrix
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [17]:
#creating a numpy array with random value
b=np.random.random((3,4))       #random value comes between 0 to 1
print(b)

[[0.16343044 0.49098779 0.62307692 0.7172333 ]
 [0.1989936  0.98520058 0.90526138 0.02576341]
 [0.54828132 0.22561635 0.10873205 0.52702269]]


In [18]:
#random integer values array with in a specific range
c=np.random.randint(10,100,(3,4))   #integer range between 10 to 100 ,,,, no of rows=3 and col=4
print(c)

[[16 21 21 43]
 [33 39 31 72]
 [88 77 99 25]]


In [19]:
#array of evenly space value--> specifiyn no of value required
d=np.linspace(10,30,5)   #here 5 is no of value required
print(d)

[10. 15. 20. 25. 30.]


In [20]:
#array of evenly spacd vaulue---. specifying the step
e=np.arange(10,30,2)   # here 2 is step
print(e)

[10 12 14 16 18 20 22 24 26 28]


In [21]:
#converting a list to numpy array
list2=[10,20,30,40,50]
print("it is list: ",list2)
np_array=np.asarray(list2)
print("it is array: ",np_array)
type(np_array)

it is list:  [10, 20, 30, 40, 50]
it is array:  [10 20 30 40 50]


numpy.ndarray

In [38]:
# is trah bhi kar sakte hai convert
list2=[10,20,30,40,50]
np_arr=np.array(list2)
print("it is array: ",np_arr)
type(np_arr)

it is array:  [10 20 30 40 50]


numpy.ndarray

In [40]:
tup2=(10,20,30,40,50)
print("it is tuple: ",tup2)
np_array=np.asarray(tup2)
print("it is array: ",np_array)
type(np_array)

it is tuple:  (10, 20, 30, 40, 50)
it is array:  [10 20 30 40 50]


numpy.ndarray

**Analysing a numpy array**




In [23]:
c=np.random.randint(10,90,(5,5))
print(c)

[[11 15 70 51 86]
 [33 74 86 56 10]
 [71 79 56 78 55]
 [40 20 73 22 15]
 [69 35 72 52 54]]


In [24]:
#array dimension
print(c.shape)

(5, 5)


In [25]:
#number of dimention
print(c.ndim)

2


In [26]:
#number of element in aarry
print(c.size)

25


In [27]:
#checking data type of values in array
print(c.dtype)

int64


**Mathmatical opration on numpy array**

In [28]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2) #concatinating list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [29]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 3 3]
 [8 3 8]
 [2 6 3]]
[[13 16 10]
 [13 16 16]
 [13 15 14]]


In [30]:
print(a+b) # addition by element wise
print(a-b)
print(a*b)
print(a/b)

[[15 19 13]
 [21 19 24]
 [15 21 17]]
[[-11 -13  -7]
 [ -5 -13  -8]
 [-11  -9 -11]]
[[ 26  48  30]
 [104  48 128]
 [ 26  90  42]]
[[0.15384615 0.1875     0.3       ]
 [0.61538462 0.1875     0.5       ]
 [0.15384615 0.4        0.21428571]]


In [31]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[0 3 0]
 [1 2 7]
 [2 3 2]]
[[12 17 14]
 [18 11 17]
 [15 18 10]]


In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[12 20 14]
 [19 13 24]
 [17 21 12]]
[[-12 -14 -14]
 [-17  -9 -10]
 [-13 -15  -8]]
[[  0  51   0]
 [ 18  22 119]
 [ 30  54  20]]
[[0.         0.17647059 0.        ]
 [0.05555556 0.18181818 0.41176471]
 [0.13333333 0.16666667 0.2       ]]


**Array Manipulation**

In [33]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 7 9]
 [9 3 4]]
(2, 3)


In [34]:
#transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[0 9]
 [7 3]
 [9 4]]
(3, 2)


In [35]:
#another way to find transpose
trans2=array.T
print(trans2)
print(trans2.shape)

[[0 9]
 [7 3]
 [9 4]]
(3, 2)


In [36]:
#reshape the array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 4 1]
 [8 8 6]]
(2, 3)


In [37]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[0 4]
 [1 8]
 [8 6]]
(3, 2)


This is the and