<a href="https://colab.research.google.com/github/Abdullah-NI/NoteBooks/blob/main/20_Working_with_matrix_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creating a matrix using numpy

In [ ]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape   #  yaha () nhi lagaya bcz ye tuple return karega       tuple' object is not callable

(2, 2)

In [ ]:
matrix_2=np.array([[2,3,4],[6,59,60],[70,37,29]])
print(matrix_2)

[[ 2  3  4]
 [ 6 59 60]
 [70 37 29]]


In [ ]:
matrix_2.shape

(3, 3)

Creating matrix with random value

In [ ]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.92562036 0.69368811 0.34323033]
 [0.69748455 0.08201449 0.13167168]
 [0.88066721 0.56783716 0.89694448]]


In [ ]:
#creating eith int
random_matrix_int=np.random.randint(100,size=(4,5))
print(random_matrix_int)

[[13 99 91 18 24]
 [32 50 71 22 23]
 [33  3 74 82 23]
 [96 88  6 31 80]]


matrix_with  all value ones

In [ ]:
matrix_ones=np.ones((2,3))
print(matrix_ones)

[[1. 1. 1.]
 [1. 1. 1.]]
