<a href="https://colab.research.google.com/github/Abdullah-NI/NoteBooks/blob/main/21_matrix_Opration_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy libraray

In [1]:
import numpy as np

**matrix Addition**

Two matrix can be added if shape is same

In [5]:
a=np.array([[2,3],[4,5]])
b=np.array([[6,7],[8,9]])
print(a)

[[2 3]
 [4 5]]


In [6]:
print(b)


[[6 7]
 [8 9]]


In [8]:
a.shape

(2, 2)

In [9]:
b.shape

(2, 2)

Adding two matrix

In [10]:
sum=a+b
print(sum)

[[ 8 10]
 [12 14]]


In [19]:
#creat two matrix with random value
matrix_1=np.random.randint(10,size=(3,3))   #less then 10
matrix_2=np.random.randint(10,20,size=(3,3))   #10 to 20 range

In [32]:
print(matrix_1)

[[7 6 5]
 [1 1 9]
 [9 8 4]]


In [33]:
print(matrix_2)

[[16 17 19]
 [12 15 11]
 [10 13 12]]


In [34]:
sum=np.add(matrix_1,matrix_2)
print(sum)

[[23 23 24]
 [13 16 20]
 [19 21 16]]


Matrix subtraction

In [23]:
a=np.array([[2,3],[4,5]])
b=np.array([[6,7],[8,9]])

In [25]:
print(a)

[[2 3]
 [4 5]]


In [26]:
print(b)

[[6 7]
 [8 9]]


In [27]:
diff=a-b
print(diff)

[[-4 -4]
 [-4 -4]]


In [28]:
#creat two matrix with random value
matrix_1=np.random.randint(10,size=(3,3))   #less then 10
matrix_2=np.random.randint(10,20,size=(3,3))   #10 to 20 range

In [29]:
print(matrix_1)

[[7 6 5]
 [1 1 9]
 [9 8 4]]


In [30]:
print(matrix_2)

[[16 17 19]
 [12 15 11]
 [10 13 12]]


In [35]:
diff=np.subtract(matrix_1,matrix_2)
print(diff)

[[ -9 -11 -14]
 [-11 -14  -2]
 [ -1  -5  -8]]


Multiply a matrix by scaler

In [36]:
x=5
y=np.random.randint(10,size=(4,4))
print(y)

[[0 0 6 3]
 [0 4 6 6]
 [3 1 0 4]
 [3 7 8 9]]


In [37]:
prod=x*y

In [38]:
print(prod)

[[ 0  0 30 15]
 [ 0 20 30 30]
 [15  5  0 20]
 [15 35 40 45]]


Multipliying two matrix

In [49]:
matrix_3=np.random.randint(5,size=(3,3))   #less then 10
matrix_4=np.random.randint(5,size=(3,4))

In [50]:
print(matrix_3)

[[1 0 1]
 [2 3 4]
 [4 2 4]]


In [51]:
print(matrix_4)

[[2 4 1 3]
 [1 3 3 0]
 [2 1 4 2]]


In [52]:
prod=np.dot(matrix_3,matrix_4)
print(prod)

[[ 4  5  5  5]
 [15 21 27 14]
 [18 26 26 20]]


In [53]:
prod.shape

(3, 4)

<h1>**Element wise multiplication**</h1>

In [58]:
matrix_3=np.random.randint(5,size=(3,3))   #less then 10
matrix_4=np.random.randint(5,size=(3,3))

In [59]:
print(matrix_3)

[[4 1 4]
 [1 0 0]
 [4 3 2]]


In [60]:
print(matrix_4)

[[3 1 3]
 [1 2 0]
 [4 0 4]]


In [61]:
prod=np.multiply(matrix_3,matrix_4)
print(prod)

[[12  1 12]
 [ 1  0  0]
 [16  0  8]]


In [62]:
# ya ese kar sakte hai
prod=matrix_3*matrix_4
print(prod)

[[12  1 12]
 [ 1  0  0]
 [16  0  8]]
